export const MessagesData = [
  {
    key: 1,
    messageContent: "Meeting summary and minutes are ready",
    messageUpdated: "3 mins ago",
    messageTime: "1:55 pm",
    messageDate: "19 Jan 2024",
    messagePlace: "KL Sentral",
    agenda: [
      "Discuss the methods and structure of the document",
      "Understand the behavior of the PY file",
      "Discuss the use of GET and POST methods",
      "Discuss the API documentation",
      "Discuss the architecture diagram",
      "Discuss the use of Large Language Model (LLM)",
    ],
    "key-discussions": [
      "The team discussed the methods and structure of the document, focusing on the use of GET and POST methods.",
      "The behavior of the PY file was discussed, with emphasis on its function when it needs one GET and one POST.",
      "The team discussed the API documentation, focusing on the difference between putting it inside or not putting it inside the method.",
      "The team discussed the architecture diagram, focusing on the inputs and outputs of the system.",
      "The use of Large Language Model (LLM) was discussed, with emphasis on its impact on the GPU.",
    ],
    concerns_and_responds: [
      "Concerns were raised about the complexity of creating the document and the need for clarity. The team agreed to revise and provide better examples.",
      "Concerns were raised about the need for a dedicated folder for the file server. The team agreed to ask for a dedicated folder.",
    ],
    action_items: [
      "The team agreed to revise the document and provide better examples.",
      "The team agreed to ask for a dedicated folder for the file server.",
      "The team agreed to discuss the back-end architecture in the next meeting.",
      "The team agreed to post the list of things to discuss in the next meeting.",
    ],
  },
  {
    key: 2,
    messageContent: "Meeting summary and minutes are ready",
    messageUpdated: "7 days ago",
    messageTime: "3.45 pm",
    messageDate: "12 Jan 2024",
    messagePlace: "KL Sentral",
  },
  {
    key: 3,
    messageContent: "Meeting summary and minutes are ready",
    messageUpdated: "14 days ago",
    messageTime: "5.15 pm",
    messageDate: "5 Jan 2024",
    messagePlace: "KL Sentral",
  },
  {
    key: 4,
    messageContent: "Meeting summary and minutes are ready",
    messageUpdated: "21 days ago",
    messageTime: "2.35 pm",
    messageDate: "28 Dec 2024",
    messagePlace: "KL Sentral",
  },
];
